### ISSUE TITLE
Create Schema for shopcart

### ISSUE THREAD

**Issue by heejungRyu** [NYUDevOps-Fall18-Shopcarts/shopcarts#17]
**As a** developer 
**I need** a schema for saving shopcart data
**So that** I can keep track of the shopcart of all users

**Assumptions :**
- Each product has an associated product-id and each user has an associated user-id

**Acceptance Criteria :**
```
Given user-id of a user
When I issue a query using that user-id
Then I should get back product-id of the products in shopcart of given user
```

**Comment by Samidha95** [comment]
**The schema for database will be as follows:**
* Columns - product-id, user-id, quantity, price
* Primary key for this table will be - product-id, user-id
