### ISSUE TITLE
POST method modifies the resource

### ISSUE THREAD

**Issue by Samidha95** [NYUDevOps-Fall18-Shopcarts/shopcarts#54]
If you send the same POST request with same data twice, the quantity of that product in shopcart is increased by one.

**Steps to reproduce**
Send a ```POST /shopcarts``` to create a add a new item. Send the same request with same data again.

**Expected Result**
Should not modify the resource

**Observed result**
Modifies the quantity of the resource by increasing it by 1

**Comment by heejungRyu** [comment]
Then do we have to return the customized error message for this?
such as "you already have that item"??

**Comment by Samidha95** [comment]
Yes, we can return that custom error message and can add suggest that user can use update functionality to modify quantity of that product in shopcart.
